# Tennis Scoring System Application Configuration
# 網球計分系統應用程式配置

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring:
  application:
    name: tennis-scoring-system
  
  # Profile configuration
  profiles:
    active: dev
  
  # Jackson JSON configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Taipei

  # Validation configuration
  validation:
    enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    com.tennisscoring: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/tennis-scoring-system.log
    max-size: 10MB
    max-history: 30

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Management endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Application specific configuration
tennis-scoring:
  match:
    # Maximum number of matches that can be stored in memory
    max-matches: 1000
    # Auto-cleanup completed matches after days
    cleanup-after-days: 30
  
  scoring:
    # Enable tiebreak at 6-6 games
    tiebreak-enabled: true
    # Minimum points to win tiebreak
    tiebreak-min-points: 7
    # Minimum lead to win tiebreak
    tiebreak-min-lead: 2
  
  api:
    # API rate limiting (requests per minute)
    rate-limit: 100
    # Enable CORS for development
    cors-enabled: true
    # Allowed origins for CORS
    cors-origins: "http://localhost:3000,http://localhost:8080"

# Info for actuator
info:
  app:
    name: Tennis Scoring System
    description: 網球計分系統 - 提供 Web API 管理單打網球比賽計分
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17
  build:
    artifact: tennis-scoring-system
    group: com.tennisscoring